### ISSUE TITLE
Content Misalignment

### ISSUE THREAD

**Issue by Utsavdc** [Shreejanshres/Herald-collab-client#3]
Contents in login page isn't aligned perfectly center.

**Comment by Shishirthapaa** [comment]
I have fixed this issue 
![Screenshot 2023-04-01 181458](https://user-images.githubusercontent.com/128440154/229331523-e5f2aebd-396b-4128-b7c8-d8344c75720e.png)

**Comment by Utsavdc** [comment]
Thank you
